name: buildkite
on: [push]
jobs:
    build:
        name: run bk
        runs-on: ubuntu-latest
        steps:
            - name: Trigger a BuildKite Build
              run: |
                TOKEN=${{secrets.BUILDKITE}} bash -c "`curl -sL https://raw.githubusercontent.com/buildkite/agent/main/install.sh`"
                ~/.buildkite-agent/bin/buildkite-agent start


